<p align="center">
  <span style="color:Navy; font-size:200%; font-weight:bold; vertical-align:middle;">
    Herramientas Computacionales Avanzadas
  </span>
  <img src="attachment:image.png" alt="ENCiT" width="220" style="vertical-align:middle; margin-left:20px;"/>
</p>

<p align="center" style="line-height:1.2;">
  <span style="color:RoyalBlue; font-size:150%;">Tema 1: Introducción</span><br/>
  <span style="color:DodgerBlue; font-size:130%;">Notebook: Numpy y arreglos</span><br/>
  <span style="font-size:100%;color:forestgreen"> Escuela Nacional de Ciencias de la Tierra  |  Semestre 2026-II</span>
</p>

---

##  ¿Qué es NumPy?

**NumPy** (*Numerical Python*) es una librería fundamental para el cálculo científico en Python.  
Permite trabajar con:
- Arreglos multidimensionales (vectores, matrices, cubos de datos).  
- Funciones matemáticas eficientes.  
- Operaciones rápidas sobre grandes volúmenes de datos.  



---



El estándar de la comunidad es importar NumPy como `np`, que funciona como una abreviatura:

```python
import numpy as np

```

In [2]:
import numpy as np

---

Ahora podemos empezar a trabajar con **NumPy**.  
En la celda anterior lo importamos, pero cambiamos su nombre: pasó de ser `numpy` a `np`.  
👉 Ese alias podría haber sido cualquier cosa, pero por **convención internacional** se usa `np`.

---

### ¿Qué es un arreglo?

🔹 **`np.array()`**  
Es la función de NumPy que permite **crear un arreglo** a partir de una lista o lista de listas de Python.  
Al usarla, obtenemos un objeto de tipo `np.ndarray`.  

🔹 **`np.ndarray`**  
Es la **clase fundamental de NumPy**, la que define a los arreglos de **N dimensiones**.  
Cada arreglo de NumPy (ya sea vector, matriz o cubo de datos) es en realidad un objeto `ndarray`.  

---

En resumen:  
- Usamos **`np.array()`** para construir arreglos.  
- El resultado es un **objeto `np.ndarray`**, que puede tener 1, 2 o más dimensiones.  
- Todos los elementos de un arreglo son del **mismo tipo**, lo que hace posible operaciones rápidas y vectorizadas.

---

#### Vamos a crear nuestro primer arreglo


In [3]:
# Creamos un arreglo de 1 al 3
arreglo=np.array([1,2,3])

In [4]:
print(arreglo)

[1 2 3]


In [5]:
# funcion type nos dice el tipo de objeto con el que estamos trabajando
print(type(arreglo))

<class 'numpy.ndarray'>


In [6]:
lista=[1, 2, 3, 4, 5]

In [7]:
# Desde una lista de Python
arr1 = np.array(lista)
print(arr1)

[1 2 3 4 5]


In [8]:
# Arreglos con ceros, unos o valores definidos
arr2 = np.zeros(5)
arr3 = np.ones((2,3))   # matriz 2x3 de unos

In [9]:
arr2

array([0., 0., 0., 0., 0.])

In [10]:
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
# seleccionando la posicion 1
arreglo[1]

2

👉 A diferencia de una lista de Python, un **arreglo de NumPy** (`ndarray`) está optimizado para almacenar datos numéricos y realizar operaciones de manera vectorizada, o sea se rápida.

### **<font color="DarkOrange"> Números aleatorios con NumPy (lo básico) </font>**

La forma más simple de generar aleatorios en NumPy es usando el módulo `np.random`.  
Primero, **fija una semilla** para que los resultados sean reproducibles:

```python
import numpy as np
np.random.seed(0)  # siempre obtendrás los mismos aleatorios al ejecutar este notebook
```

In [11]:
# Un número aleatorio
x = np.random.rand()
print("x =", x)

x = 0.19970159384127983


In [12]:
# Un vector de 5 aleatorios
v = np.random.rand(5)
print("v =", v)

v = [0.59232069 0.74923598 0.33592072 0.39868101 0.49666847]


In [14]:
# Una matriz 2x3 de aleatorios
M = np.random.rand(2, 3)
print("M =\n", M)

M =
 [[0.17796911 0.85607788 0.0235442 ]
 [0.40344415 0.09115878 0.92438672]]


In [24]:
# Un entero entre 0 y 9 (10 no incluido)
n = np.random.randint(0, 10)
print("n =", n)

n = 5


In [25]:
# 3 enteros entre 0 y 9 (10 no incluido)
n = np.random.randint(0, 10,3)
print("n =", n)

n = [7 3 6]


---

##  ¿Qué es un atributo en Python?

En Python, los **objetos** (como los arreglos de NumPy) tienen **atributos**:  
propiedades o características que describen al objeto.  

Ejemplo en la vida diaria:  
Un “arreglo de datos” es como una **tabla de Excel**. Sus atributos serían:  
- el número de filas y columnas,  
- cuántos elementos contiene,  
- de qué tipo son los datos.  

En **JupyterHub**, puedes explorar los atributos de un objeto escribiendo su nombre y luego dos veces la tecla `TAB`.  
Esto muestra la lista de métodos y atributos disponibles.

---

## Atributos de un arreglo en NumPy

Volvamos a nuestro primer arreglo y revisemos algunos de sus atributos:

```python
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Arreglo:\n", arr)
print("Número de dimensiones (ndim):", arr.ndim)
print("Forma (shape):", arr.shape)
print("Número de elementos (size):", arr.size)
print("Tipo de datos (dtype):", arr.dtype)


### <font color="DarkOrange">Creación de arreglos básicos: `linspace` vs `arange`</font>

*Idea clave:* ambos generan secuencias numéricas, pero con enfoques distintos.

- **`np.linspace(inicio, fin, num)`**  
  Eliges **cuántos puntos** quieres. Por defecto son 100 e **incluye** el `fin`.
  - Útil para mallas uniformes con un número exacto de muestras (tiempo, profundidad, longitudes).
  - Evita errores de redondeo en pasos decimales.

- **`np.arange(inicio, fin, paso)`**  
  Eliges el **tamaño del paso**. El arreglo es semiabierto: incluye `inicio`, **excluye** `fin`.
  - Ideal con pasos enteros (índices, días, conteos).
  - Con pasos decimales puede acumular errores de punto flotante.

---

In [28]:
# inicio,fin = 0,10
con_linespace=np.linspace(0,10)
print(con_linespace)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [30]:
# inicio,fin = 0,10 pero no incluye el 10
con_arange=np.arange(0,10)
print(con_arange)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
# 5 puntos entre 0 y 10 (incluye el 10)
x = np.linspace(0, 10, num=5)           # -> [ 0., 2.5, 5., 7.5, 10.]

In [ ]:
# Días 1 al 7 (enteros)
dias = np.arange(1, 8)  

---
<a name='ej-1'></a>
### **<font color="DodgerBlue">Ejercicio 1 - `arange` vs `linspace` </font>**

<font color="DarkBlue"> Genere un arreglo que vaya de -5 a 5 y que tenga al menos 50 elementos, incluyendo los dos extremos, el -5, y el 5.

---

---


### <font color="DarkOrange">Arreglos 2D y nD en NumPy</font>

Hasta ahora hemos trabajado principalmente con **arreglos 1D** (vectores).  
Sin embargo, la verdadera potencia de NumPy se aprecia al usar **arreglos de dos o más dimensiones**.

- Un **arreglo 2D** se puede pensar como una **tabla o matriz**: filas × columnas.  
  Ejemplo: datos meteorológicos de varias estaciones a lo largo de varios días.  

- Un **arreglo nD** extiende la idea a tres o más dimensiones:  
  - 3D: una pila de matrices (ejemplo: mapas de temperatura para diferentes meses).  
  - 4D o más: series temporales de datos espaciales y multivariados (ejemplo: temperatura atmosférica en niveles verticales y distintos tiempos).  

---

### Relevancia en Ciencias de la Tierra
Los arreglos multidimensionales son esenciales porque los datos que usamos rara vez son listas simples.  
Al contrario, suelen organizarse en **estructuras espaciales y temporales**:

- Tablas con estaciones y variables meteorológicas.  
- Mapas 2D de precipitación, temperatura o calidad del aire.  
- Cubos 3D o 4D que integran espacio (latitud, longitud, altura) y tiempo.  

NumPy nos permite **almacenar, manipular y analizar** todos estos datos de manera eficiente.

---

In [7]:
# creamos el arreglo
arreglo_2D=np.array([[1,2,3],[4,5,6]])
# imprimimos el arreglo
print('Arreglo 2D')
print(arreglo_2D)
# aqui imprimimos las formas del arreglo 1 y el 2
print(arreglo_2D.shape,arreglo.shape)

Arreglo 2D
[[1 2 3]
 [4 5 6]]
(2, 3) (3,)


In [8]:
arreglo_2D.size

6

---

### 🔪 Slicing

En Python, para **seleccionar elementos** de un arreglo de NumPy (lo que se conoce como *slicing*), se utiliza la **notación de corchetes** `[]`.  

Recuerda que **Python usa indexación basada en cero**, es decir, el primer elemento de un arreglo tiene índice `0`.

---

#### Sintaxis general

[inicio:fin:paso]

- **inicio** → índice donde comienza el corte (incluido).  
- **fin** → índice donde termina el corte (excluido).  
- **paso** → cada cuántos elementos se toma uno (opcional).  



In [9]:
arr = np.array([10, 20, 30, 40, 50])

In [10]:
print(arr[0])      # primer elemento → 10
print(arr[1:4])    # del índice 1 al 3 → [20 30 40]
print(arr[::2])    # de inicio a fin, cada 2 → [10 30 50]

10
[20 30 40]
[10 30 50]


In [11]:
# Crear un arreglo bidimensional (matriz)
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Matriz')
print(matriz)

Matriz
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# Seleccionar la primera fila (índice 0)
primera_fila = matriz[0, :]

In [13]:
# Seleccionar la segunda columna (índice 1)
segunda_columna = matriz[:, 1]

In [14]:
# Seleccionar un subconjunto de la matriz
submatriz = matriz[1:3, 0:2]

---
<a name='ej-1'></a>
### **<font color="DodgerBlue">Ejercicio 3 - *¿En qué dimensión estamos?* </font>**

<font color="DarkBlue"> 1. Genere un arreglo de numpy de 3 dimensiones de la forma (3,2).

<font color="DarkBlue"> 2. Luego obtenga a través de un slice, o una submatriz, el elemento que se encuentra en la segunda fila primer columna.

---


---

### Operaciones básicas con arreglos

Una de las grandes ventajas de **NumPy** es que permite realizar operaciones directamente sobre arreglos completos, sin necesidad de escribir bucles.  
A esto se le llama **vectorización**: aplicar una operación a todos los elementos de un arreglo de manera automática y eficiente.

---

#### Operaciones elemento a elemento
Los operadores aritméticos funcionan de forma natural en arreglos:

- `+` → suma  
- `-` → resta  
- `*` → multiplicación  
- `/` → división  
- `**` → potencia

Ejemplo:

```python
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(a + b)   # [11 22 33 44]
print(a * b)   # [10 40 90 160]
print(a ** 2)  # [ 1  4  9 16]


In [15]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

In [16]:
print(a + b)   # []

[11 22 33 44]


In [17]:
print(a * b)   # []
print(a ** 2)  # []

[ 10  40  90 160]
[ 1  4  9 16]


---

### Operaciones prefabricadas en NumPy

Además de las operaciones aritméticas básicas, **NumPy** incluye muchas funciones ya “prefabricadas” para calcular propiedades de los datos de manera rápida y eficiente.  
Estas funciones actúan directamente sobre los arreglos, sin necesidad de escribir ciclos.

---

#### 1. `np.mean()` → promedio
Calcula el valor medio de todos los elementos del arreglo.

```python
arr = np.array([2, 4, 6, 8, 10])
print(np.mean(arr))   # 6.0


#### 2 .`np.sum()` → suma
Calcula la suma de todos los elementos del arreglo.

In [18]:
print(np.sum(arr)) 

150


#### 3. `np.max()` → maximo
Calcula el máximo valor del arreglo.

In [19]:
print(np.max(arr))

50


---

### Operaciones por *axis* en NumPy

Las funciones de NumPy, como `np.mean`, `np.sum` o `np.max`, pueden aplicarse a todo el arreglo **o a lo largo de un eje específico**.  
Ese eje se indica con el argumento `axis`.

---

#### ¿Qué significa `axis`?
- En un **arreglo 2D** (matriz):
  - `axis=0` → opera **a lo largo de las filas**, es decir, combina los valores **columna por columna**.  
  - `axis=1` → opera **a lo largo de las columnas**, es decir, combina los valores **fila por fila**.  

En otras palabras:  
- `axis=0` → reduce el arreglo verticalmente.  
- `axis=1` → reduce el arreglo horizontalmente.  

---

#### Ejemplo 





In [20]:
mat = np.array([[1, 2, 3],
                [-4, 5, 6],
                [7, 8, -9]])
print("Matriz:\n", mat)

Matriz:
 [[ 1  2  3]
 [-4  5  6]
 [ 7  8 -9]]


In [21]:
# Promedio de cada columna (axis=0)
print("Promedio por columna:", np.mean(mat, axis=0))  

# Promedio de cada fila (axis=1)
print("Promedio por fila:", np.mean(mat, axis=1))  

Promedio por columna: [1.33333333 5.         0.        ]
Promedio por fila: [2.         2.33333333 2.        ]


In [22]:
# Máximo por columna
print("Máximos por columna:", np.max(mat, axis=0))

# Suma de cada fila
print("Suma por fila:", np.sum(mat, axis=1))

Máximos por columna: [7 8 6]
Suma por fila: [6 7 6]


---
<a name='ej-3'></a>
### **<font color="DodgerBlue">Ejercicio 4: *Suma que suma* </font>**

<font color="DarkBlue"> Considerando el arreglo 2D visto anteriormente `mat`, calcule lo siguiente:

1. Suma de todo el arreglo
2. Suma por columna
3. Suma por fila
4. Evalúe cual de todos estos valores obtenidos es el más grande, o el valor máximo.

---